services:
  back-end:
    build: 
      context: tutorialspring
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://mysql-db/fullstack
      DB_USERNAME: example_user
      DB_PASSWORD: password123 
    depends_on:
      - mysql-container
  front-end:
    build:
      context: studentfrontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - back-end
  mysql-container:
    image: mysql:8.0.33-oracle
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fullstack
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123

volumes:
  dbdata:
    
